language: node.js
node_js:
  - "10"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: A2FSdRslmvlFvQbGU45JQSen5jlwE5u8Uw4wiXF193eyjUtORbXmJem2DhyFjSHCkmBxvSXFF5wRK6FGJ4GAEpupATIxoAIwTF5KpE1WfDEcjayb1O1qhud+c5GR7WeVEBkzHzd6WV9Q7uRIJdrMiD3xjRSqpjYlPqyUxNgjJ+PIilaq7pNbqn8x6t5tkBQGboVA7x3lWi5LnRf9xrs4jiXhqTvqujEwupusT+rHTX+cxFIXn6Qd/CnNX8m8ndCrsI9odKeRykY6h4JziI1bfMvZCFFHfkz3LZs+AGB/7MCEL9XsA26tR2X46TNPyOFkSVhGj3/lggrxmOtpnaTNrZEFCZc1KWr8tmPIqUkJYnaAJtKAV9FCHuvkwbgbRLxD6w7eFnAUxoiip7WrV4VbxRxoTQfvD8gv45Wjj0p7XHrqWinEnF2TrAxBKkGSuY2JbyK0yLVKIGzbTT96sj79AF18uIJS2vZrlWdSEs8Gl0G4ALqCjEOVG5Dc6CibmBqgbbrYYqSZut9xBIfLz6w5jrnFOlBC2iD0otx1GHTUkCmP47kpIdrVZj3U4AhnxehhEJZiVg1kzafSETmGR/zyWazMtAL9A9dWhPKlH8l9LqPMnF4MyXpbBygBjZZqYR5QQ6OT1b/N5HSfOTogNwPtVvP0cbNA2E2HEkuG0+NfnQ4=
  app: exam-maker-backend
  on:
    repo: exam-simulator/maker-backend
